"""initial schema

Revision ID: 2c95530c6343
Revises:
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2c95530c6343"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_event",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("subject", sa.String(length=256), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_event")),
    )
    op.create_table(
        "ingested_file",
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("coverholder", sa.String(length=128), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("family", sa.String(length=32), nullable=False),
        sa.Column("mapping_version", sa.Integer(), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=True),
        sa.Column("row_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("quarantined_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("object_key", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("content_hash", name=op.f("pk_ingested_file")),
    )
    op.create_table(
        "mapping_contract",
        sa.Column("coverholder", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("family", sa.String(length=32), nullable=False),
        sa.Column("columns", sa.JSON(), nullable=False),
        sa.Column("confirmed_by", sa.String(length=128), nullable=False),
        sa.Column(
            "confirmed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("digest", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("coverholder", "version", name=op.f("pk_mapping_contract")),
    )
    op.create_table(
        "ledger_row",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_content_hash", sa.String(length=64), nullable=False),
        sa.Column("mapping_version", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=256), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("gross", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("deductions", sa.JSON(), nullable=False),
        sa.Column("net", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("lineage", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_content_hash"],
            ["ingested_file.content_hash"],
            name=op.f("fk_ledger_row_source_content_hash_ingested_file"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_row")),
        sa.UniqueConstraint(
            "source_content_hash",
            "mapping_version",
            "key",
            name="one_row_per_key_per_mapping_version",
        ),
    )
    op.create_table(
        "quarantine",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_content_hash", sa.String(length=64), nullable=False),
        sa.Column("spreadsheet_row", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("raw_value", sa.Text(), server_default="", nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_content_hash"],
            ["ingested_file.content_hash"],
            name=op.f("fk_quarantine_source_content_hash_ingested_file"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quarantine")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quarantine")
    op.drop_table("ledger_row")
    op.drop_table("mapping_contract")
    op.drop_table("ingested_file")
    op.drop_table("audit_event")
    # ### end Alembic commands ###
