"""The manifest: the one file the evaluation lane reads, and the hold-out split it reads from it.

**The split is a committed rule, not a decision.** ADR-001 fixes it before any score exists, and
for one reason: project 3 in this portfolio published a development F1 of 0.963 and a held-out F1
of 0.328, and the only thing that made the second number believable was that nobody could have
chosen it. The rule has two clauses, both fixed here:

1. **Hash of the variant identifier.** `blake2b(variant_id) % 100 < 30`. No seed, so it cannot be
   re-rolled; no scores in it, so it cannot be re-drawn after a disappointing one. Renaming a
   variant to move it across the line is a visible edit to a committed catalogue.
2. **Any variant declaring `vocabulary_is_unseen` is held out.** ADR-001 requires at least one
   hold-out variant whose headers appear nowhere in development, and a pure hash cannot promise
   that. This clause is declared in the catalogue before generation, not selected afterwards, and
   :func:`verify_split` fails the build if the promise turns out to be false — if a supposedly
   unseen header does appear in a development variant, generation stops rather than publishing a
   hold-out that is quietly contaminated.

**The hold-out is whole variants, never rows.** Holding out rows from a layout the mapper has
already been tuned against measures nothing at all: the mapping is per layout, so a held-out row
from a seen layout is a row whose answer is already known.

**Mapping accuracy is scored over mappable variants only.** The two unmappable ones have no true
mapping to be accurate about — their correct output is a quarantine — so `unmappable` is published
per variant and the denominator is the evaluator's to get right.
"""

from __future__ import annotations

import hashlib
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Final

from bordereaux_reconciler.corpus.variants import VariantSpec

__all__ = [
    "GENERATED_AT",
    "GENERATOR_VERSION",
    "HOLDOUT_RULE",
    "SEED",
    "VariantRecord",
    "assemble",
    "corpus_digest",
    "is_held_out",
    "verify_split",
]

#: Bumped whenever a change would alter generated bytes. Every artifact carries it, so a stale
#: corpus on somebody's disk announces itself rather than being silently mixed with a fresh one.
GENERATOR_VERSION: Final = "1.0.0"

#: The published seed. One integer, and the whole corpus follows from it.
SEED: Final = 20260924

#: **A declared constant, not a wall clock.** A generator that stamped `datetime.now()` here would
#: produce a different manifest on every run, and the determinism proof — two runs, byte-identical
#: output — would be impossible by construction. Reproducibility is the stronger property, so the
#: timestamp says when this generator version was fixed rather than when it last ran. Anyone
#: needing the run time has the file's mtime.
GENERATED_AT: Final = "2026-09-24T00:00:00Z"

#: Under thirty in a hundred. Expected five or six of eighteen, plus the declared unseen ones.
_HOLDOUT_SHARE: Final = 30
_BUCKETS: Final = 100

HOLDOUT_RULE: Final = (
    "held out if blake2b(variant_id, digest_size=8) % 100 < 30, or if the variant declares "
    "vocabulary_is_unseen; assignment uses no seed and no score, so it cannot be re-drawn"
)


def is_held_out(spec: VariantSpec) -> bool:
    """Whether this variant is in the hold-out, by the rule above and nothing else."""
    if spec.vocabulary_is_unseen:
        return True
    digest = hashlib.blake2b(spec.variant_id.encode("utf-8"), digest_size=8).digest()
    return int.from_bytes(digest, "big") % _BUCKETS < _HOLDOUT_SHARE


@dataclass(frozen=True, slots=True)
class VariantRecord:
    """What the manifest publishes about one variant. The evaluator's whole view of it."""

    spec: VariantSpec
    rows: int
    source_sha256: str
    truth_sha256: str
    adversarial: tuple[str, ...]

    def to_json(self) -> dict[str, object]:
        spec = self.spec
        return {
            "variant_id": spec.variant_id,
            "family": spec.family,
            "split": "holdout" if is_held_out(spec) else "development",
            "file": spec.path,
            "truth": spec.truth_path,
            "file_format": str(spec.file_format),
            "sheet_name": spec.sheet_name,
            "rows": self.rows,
            "currency": str(spec.currency),
            "period": spec.period,
            "decimal_convention": str(spec.decimal),
            "date_format": str(spec.dates),
            "period_format": str(spec.periods),
            "currency_style": str(spec.currency_style),
            "declared_total": str(spec.total),
            "byte_order_mark": spec.byte_order_mark,
            "parenthesised_negatives": spec.parenthesised_negatives,
            "unmappable": spec.unmappable,
            "vocabulary_is_unseen": spec.vocabulary_is_unseen,
            "column_mapping": spec.column_mapping,
            "unmapped_headers": list(spec.unmapped_headers),
            "perturbations": list(spec.perturbations),
            "adversarial_cases": list(self.adversarial),
            "source_sha256": self.source_sha256,
            "truth_sha256": self.truth_sha256,
            "notes": spec.notes,
        }


def verify_split(specs: Sequence[VariantSpec], *, minimum: int) -> tuple[str, ...]:
    """Check the split honours ADR-001, and return the headers that are genuinely unseen.

    Two promises are checked rather than assumed. That the hold-out is large enough, and that the
    variants claiming an unseen vocabulary actually have one — a header shared with a development
    variant would mean the "unseen synonym" hold-out had been seen, which is the precise failure
    the split exists to prevent and the kind that is invisible unless something looks.
    """
    held_out = [spec for spec in specs if is_held_out(spec)]
    if len(held_out) < minimum:
        raise RuntimeError(
            f"the hold-out has {len(held_out)} variants and ADR-001 fixes a minimum of {minimum}. "
            "Add variants; do not move the rule."
        )

    development_headers = {
        column.header for spec in specs if not is_held_out(spec) for column in spec.columns
    }
    unseen: set[str] = set()
    for spec in specs:
        if not spec.vocabulary_is_unseen:
            continue
        leaked = {c.header for c in spec.columns} & development_headers
        if leaked:
            raise RuntimeError(
                f"{spec.variant_id} declares an unseen vocabulary but these headers also appear in "
                f"a development variant: {sorted(leaked)}"
            )
        unseen |= {c.header for c in spec.columns}

    if not unseen:
        raise RuntimeError(
            "no hold-out variant has an unseen vocabulary, so kill condition E would be measured "
            "against layouts whose header words the system has already been shown"
        )
    return tuple(sorted(unseen))


def corpus_digest(hashes: Mapping[str, str]) -> str:
    """One hash over every generated file, so two runs can be compared in a single comparison.

    Path and content together, sorted, because a corpus that produced the right bytes under the
    wrong names is not the same corpus.
    """
    joined = "\n".join(f"{path}:{digest}" for path, digest in sorted(hashes.items()))
    return hashlib.sha256(joined.encode("utf-8")).hexdigest()


def assemble(
    records: Sequence[VariantRecord],
    *,
    hashes: Mapping[str, str],
    adversarial: Sequence[str],
    unseen_headers: Sequence[str],
) -> dict[str, object]:
    """The manifest, in the order a reader would want to read it.

    `is_synthetic` and `notice` are first-class fields rather than a line in a README because
    ADR-001 forbids this corpus ever being described as real-world labelled data, and a machine-
    readable file that says so travels with the data when the README does not.
    """
    specs = [record.spec for record in records]
    return {
        "generator_version": GENERATOR_VERSION,
        "generator": "scripts/generate_corpus.py",
        "seed": SEED,
        "generated_at": GENERATED_AT,
        "generated_at_note": (
            "a declared constant fixed with the generator version, not a wall clock: a timestamp "
            "would make two runs differ in bytes and there would be no determinism claim left"
        ),
        "is_synthetic": True,
        "notice": (
            "Synthetic data, generated from a committed seed. It is not real-world labelled data "
            "and must never be described as such: no redistributable corpus of delegated-authority "
            "bordereaux exists, because those files carry commercial terms and personal data."
        ),
        "families": sorted({spec.family for spec in specs}),
        "schema_variants": len(records),
        "canonical_rows": sum(record.rows for record in records),
        "held_out_variants": sum(1 for spec in specs if is_held_out(spec)),
        "holdout_rule": HOLDOUT_RULE,
        "holdout": sorted(spec.variant_id for spec in specs if is_held_out(spec)),
        "development": sorted(spec.variant_id for spec in specs if not is_held_out(spec)),
        "unseen_headers": list(unseen_headers),
        "adversarial_cases": list(adversarial),
        "unmappable": sorted(spec.variant_id for spec in specs if spec.unmappable),
        "mappable_variants": sum(1 for spec in specs if not spec.unmappable),
        "corpus_digest": corpus_digest(hashes),
        "file_sha256": dict(sorted(hashes.items())),
        "variants": [record.to_json() for record in records],
    }
